# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [10]:
# write your code here ^_^
np.linspace(0,50,15)

array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
       17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
       35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [56]:
# write your code here ^_
Array1 = np.array(
    [
        [
            [1.1, 2.1,3.1],
            [4.1, 5.1, 6.1] ],
        [
            [7.1, 8.1,9.1], 
            [10.1,11.1,12.1]
        ]
    ])
Array1
# Array1.shape

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [22]:
# write your code here ^_^
print(Array1.shape)
print(Array1.dtype)
print(Array1.ndim)
print(Array1.size)
print(type(Array1))

(2, 2, 3)
float64
3
12
<class 'numpy.ndarray'>


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [42]:
# write your code here ^_^
Array2 =np.array([])
Array2 = Array1.reshape(2,2,3,-1)
print("The Array after changes to 4D ", Array2.shape, "and the shape is: " ,"And the dimension is: ", Array2.ndim )

The Array after changes to 4D  (2, 2, 3, 1) and the shape is:  And the dimension is:  4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [38]:
# write your code here ^_^
Array3 =np.array([])
Array3 = Array2.astype(int)
Array3

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [39]:
# write your code here ^_^
for Number in np.nditer(Array3):
    print(Number)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [41]:
# write your code here ^_^
Array3 [1,0,1]

array([8])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [43]:
# write your code here ^_^
Array3[0,1,1:]

array([[5],
       [6]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [46]:
# write your code here ^_^
Array4 = np.where(Array3 == 8 , Array3, 0)
Array4

array([[[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]],


       [[[0],
         [8],
         [0]],

        [[0],
         [0],
         [0]]]])

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [54]:
# write your code here ^_^
Array5 = Array3.shape(3,2)

TypeError: 'tuple' object is not callable

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [81]:
# write your code here ^_^

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
# arr3 = np.vstack((arr1,arr2))
arr3 = np.row_stack((arr1,arr2))
arr3

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [64]:
# write your code here ^_^
arr4 = np.array([])
arr4= np.concatenate((arr1,arr2),axis=1)
arr4


array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [83]:
# write your code here ^_^
[B,C] = np.hsplit(arr3,2)
B


array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1')

In [84]:
C

array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')