# Q1: Import numpy library

In [2]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
# write your code here ^_^

np.linspace(0.7,1,15)

array([0.7       , 0.72142857, 0.74285714, 0.76428571, 0.78571429,
       0.80714286, 0.82857143, 0.85      , 0.87142857, 0.89285714,
       0.91428571, 0.93571429, 0.95714286, 0.97857143, 1.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
# write your code here ^_^
arr3d=np.array([[[1.1,2.1,3.1], [4.1,5.1,6.1]],
               [[7.1,8.1,9.1], [10.1,11.1,12.1]]])
arr3d

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [5]:
# write your code here ^_^
print("Array's type : ",type(arr3d))
print("Array's elements datatype. :",arr3d.dtype)
print("Array's shape. : ",arr3d.shape)
print("Array's size : ",arr3d.size)
print("Array's dimention : ",arr3d.ndim)

Array's type :  <class 'numpy.ndarray'>
Array's elements datatype. : float64
Array's shape. :  (2, 2, 3)
Array's size :  12
Array's dimention :  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [6]:
# write your code here ^_^

arr4d=np.expand_dims(arr3d, axis=0)  # Or Just add ']' 
print("NewShape : ",arr4d.shape)
print("New Dimention : ",arr4d.ndim)

NewShape :  (1, 2, 2, 3)
New Dimention :  4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [7]:
# write your code here ^_^

arr4d_int=arr4d.astype("int")
arr4d_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [8]:
# write your code here ^_^

for n in np.nditer(arr4d_int):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [9]:
arr4d_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [18]:
# write your code here ^_^

arr4d_int[0,1,0,1:2]

array([8])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [11]:
# write your code here ^_^

arr4d_int[0,0,1,1:]

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [12]:
# write your code here ^_^

np.where(arr4d_int==8)

(array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [13]:
# write your code here ^_^

arr4d_int.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [14]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [15]:
# write your code here ^_^
all_arr=np.row_stack((arr1,arr2))
all_arr.shape

(4, 2)

# Q12.2: Join the arrays along rows with axis = 1 

In [16]:
# write your code here ^_^

all_arr2 = np.concatenate((arr1, arr2), axis=1)
all_arr2.shape


(2, 4)

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [17]:
# write your code here ^_^

S= np.split(all_arr, 2,axis=1)
S

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]